import Head from 'next/head'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import {useTranslation} from 'next-i18next';
import {ReactElement} from 'react';
import AppLayout from '../components/layouts/app';
import ThemeChanger from '../components/ui/ThemeChanger';


// noinspection JSUnusedGlobalSymbols
export async function getStaticProps({ locale }: {locale: string}) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common', 'footer'])),
      // Will be passed to the page component as props
    },
  };
}

const Home = () => {
  const {t} = useTranslation(['common'])

  return (
    <div>
      <Head>
        <title>{t('common:title')}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Home</div>
      <ThemeChanger/>
    </div>
  )
}

Home.getLayout = function getLayout(page: ReactElement) {
  return (
    <AppLayout>
      {page}
    </AppLayout>
  )
}

export default Home
